name: Upstream Sync

permissions:
  contents: write
  issues: write
  actions: write

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:
    inputs:
      ignore_files:
        description: 'Files to ignore during sync (comma-separated)'
        required: false
        default: 'CHANGELOG.md'
        type: string

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean issue notice
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          labels: '🚨 Sync Failed'

      - name: Extract ignore files
        id: extract_ignore
        run: |
          # Default files to ignore
          DEFAULT_IGNORE="Changelog.md"

          # Get input files to ignore or use default
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            IGNORE_FILES="${{ github.event.inputs.ignore_files }}"
          else
            IGNORE_FILES="$DEFAULT_IGNORE"
          fi

          # Convert to array and prepare for output
          echo "IGNORE_FILES=$IGNORE_FILES" >> $GITHUB_ENV
          echo "ignore_files=$IGNORE_FILES" >> $GITHUB_OUTPUT

          # Create a backup of files to be preserved
          mkdir -p .file_backup
          for file in $(echo $IGNORE_FILES | tr ',' ' '); do
            if [ -f "$file" ]; then
              echo "Backing up $file"
              cp "$file" .file_backup/ || true
            fi
          done

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: lobehub/lobe-chat
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Restore ignored files
        if: steps.sync.outputs.has_new_commits == 'true'
        run: |
          # Restore files from backup
          for file in $(echo $IGNORE_FILES | tr ',' ' '); do
            if [ -f ".file_backup/$file" ]; then
              echo "Restoring $file"
              cp ".file_backup/$file" "$file"
              git add "$file"
            fi
          done

          # Commit the restored files if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Restore ignored files after sync: ${{ steps.extract_ignore.outputs.ignore_files }}"
            git push
          fi

      - name: Sync check
        if: failure()
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          title: '🚨 Sync Failed'
          labels: '🚨 Sync Failed'
          body: |
            Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork.

            To manually sync your fork:
            1. Go to your fork's GitHub page
            2. Click on "Sync fork" button
            3. Click on "Update branch"

            If you encounter any issues, please contact the repository maintainers.

      - name: Trigger Release Workflow
        if: success() && steps.sync.outputs.has_new_commits == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/release.yml/dispatches \
            -d '{"ref":"main"}'
